# EC2 variables
instance_type: t2.small
ami_id: ami-0b898040803850657
region: us-east-1
count: 1
wait: true
security_groups: sg-086a32d41ee5dd15f
vpc_subnet_id: subnet-098f1c7f
instance_tags: '{"Name":"netbox"}'
launch_user_group: devops
launch_user: user1
app_name: netbox
