---
- name: Bootstrap AWS
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Creating SSH Key
      shell: |
        ssh-keygen -b 2048 -t rsa -f ~/.ssh/ansible.pem -q -N '' && \
        chmod 0600 ~/.ssh/ansible.pem.pub
      args:
        chdir: ~/.ssh/
        creates: ansible.pem

    - name: Creating EC2 Key Pair
      ec2_key:
        name: ansible
        state: present
        region: "{{ region }}"
        key_material: "{{ item }}"
      with_file: ~/.ssh/ansible.pem.pub

    - name: Evaluating the authentication agent & adding the key...
      shell: |
        eval "$(ssh-agent)"
        ssh-agent bash
        ssh-add ~/.ssh/ansible.pem

    - name: Creating Security Group
      ec2_group:
        name: netbox
        description: SSH Access
        state: present
        region: "{{ region }}"
        rules:
          - proto: tcp
            to_port: 22
            from_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launching EC2 Instance
      ec2:
        group: netbox
        image: "{{ image }}"
        instance_type: t3.small
        instance_initiated_shutdown_behavior: terminate
        key_name: ansible
        wait: yes
        region: "{{ region }}"
        state: present
        volumes:
          - device_name: /dev/xvda
            delete_on_termination: true
            volume_size: 32
            volume_type: gp2
        instance_tags:
          Name: netbox
      register: ec2

    - name: Registering Host
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: aws
      with_items: "{{ ec2.instances }}"

    - name: Waiting for SSH
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        timeout: 120
        state: started
      with_items: "{{ ec2.instances }}"

- name: AWS
  user: ec2-user
  hosts: aws
  become: true
  become_user: root
  gather_facts: true
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8

- name: Teardown AWS
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Deleting EC2 Key Pair
      ec2_key:
        name: ansible
        state: absent
        region: "{{ region }}"

    - name: Deleting SSH Key
      file:
        path: "../{{ item }}"
        state: absent
      with_items:
        - ~/.ssh/ansible.pem.pub
