---
- name: Bootstrap AWS
  hosts: localhost
  gather_facts: false
  vars:
    key_name: ansible-netbox
  roles:
    - role: netbox-ami-setup

- name: AWS
  user: ec2-user
  hosts: aws
  become: true
  become_user: root
  gather_facts: true
  environment:
    LANG: en_US.UTF-8
    LC_ALL: en_US.UTF-8
  vars:
    netbox_version: 2.6.3
    db_name: netbox
    db_host: "127.0.0.1"
    db_user: netbox
    region: us-east-1
    server_name: netbox.sample.com
    # active_groups:
    #   - "CN=IPAM ReadOnly,OU=Operations,DC=sample,DC=com"
    #   - "CN=IPAM ReadWrite,OU=Operations,DC=sample,DC=com"
    #   - "CN=IPAM Admin,OU=Operations,DC=sample,DC=com"
    # staff_group: "CN=IPAM Admin,OU=Operations,DC=sample,DC=com"
  pre_tasks:
    - name: lookup credentials
      set_fact:
        auth:
          db_pass: "kjjejciekcjle"
          secret_key: "fdaeckasnckajsecer"
          netbox_user: "username"
          netbox_pass: "password"
          netbox_email: "fartbagxp@gmail.com"
  roles:
    - role: aws-ami
    - role: netbox
    - role: nginx
    - role: gunicorn

- name: Teardown AWS
  hosts: localhost
  gather_facts: false
  vars:
    key_name: ansible-netbox
  roles:
    - role: netbox-ami-teardown
